var Dictionary = [
	{ fr : 'a', kanji: 'あ', lvl:1, rank:1},
	{ fr : 'e', kanji: 'え', lvl:1, rank:1},
	{ fr : 'i', kanji: 'い', lvl:1, rank:1},
	{ fr : 'o', kanji: 'お', lvl:2, rank:1},
	{ fr : 'u', kanji: 'う', lvl:3, rank:1},
	{ fr : 'ka', kanji: 'か', lvl:4, rank:2},
	{ fr : 'ke', kanji: 'け', lvl:5, rank:2},
	{ fr : 'ki', kanji: 'き', lvl:6, rank:2},
	{ fr : 'ko', kanji: 'こ ', lvl:7, rank:2},
	{ fr : 'ku', kanji: 'く', lvl:8, rank:2},
	{ fr : 'sa', kanji: 'さ', lvl:9, rank:3},
	{ fr : 'se', kanji: 'せ', lvl:10, rank:3},
	{ fr : 'shi', kanji: 'し', lvl:11, rank:3},
	{ fr : 'so', kanji: 'そ', lvl:12, rank:3},
	{ fr : 'su', kanji: 'す', lvl:13, rank:3},
	{ fr : 'ta', kanji: 'た', lvl:14, rank:4},
	{ fr : 'te', kanji: 'て', lvl:15, rank:4},
	{ fr : 'chi', kanji: 'ち', lvl:16, rank:4},
	{ fr : 'to', kanji: 'と', lvl:17, rank:4},
	{ fr : 'tsu', kanji: 'つ', lvl:18, rank:4}
];